### ISSUE TITLE
Environment Variables in Tupfiles

### ISSUE THREAD

**Issue by bradjc** [gittup/tup#103]
Is it possible to access environment variables inside Tupfiles? This need comes from referencing `run` command scripts. For example, if my environment variable name is `SCRIPT_DIR`, I'd like to be able to write a Tupfile like:

```
run $(SCRIPT_DIR)/my_script.py
```

Perhaps Tup already supports this, but I scoured the manual and couldn't find it.

**Comment by eddyp** [comment]
@Qix- : Thanks for the info. My point is that an even more permissive, say `exportall`, to propagate everything would be useful. Please consider implementing this.

**Comment by tschmid** [comment]
I assume this has not been implemented yet, as the issue is still open, and I wanted to start this discussion back up. 

We have a need for this in our development environment. We are developing a Wireless System and would like to use different default radio channels for each developer. The easiest way is to have an environment variable, like DEFAULT_CHANNEL=18, that then gets passed down to gcc as -DDEFAULT_CHANNEL=18.

I really like the simple:

import CC=gcc

notation.

**Comment by KamilSzczygiel** [comment]
+1 on this (;

**Comment by royshea** [comment]
Another +1 on this.

**Comment by rulatir** [comment]
Qix's bootstrap-script.sh solution proves that the inability to use variables to specify the location of a run script fits the definition of a Completely Stupid Limitation. A Completely Stupid Limitation is one which:

- can actually be overcome by an ingenious user, at the cost of code size and legibility and gray hair
- overcoming it in this manner doesn't have any negative consequences; the limitation is thus *proven* to be there just for the heck of it, not because it protects the user from a potential disaster

The Only Right Thing to do with a Completely Stupid Limitation is to Just Remove It, Full Stop.

**Comment by gittup** [comment]
Sorry it took so long, but 'import FOO' and 'import FOO=bar' (to set a default if it's not set in the environment) is now on the master branch. File an issue if you have any problems with it.

**Comment by gittup** [comment]
> It works great for me so far slightly_smiling_face (both with and without default value), do you think it's ready to be merged?

Merged where? It should be on master already.

**Comment by xpac27** [comment]
Indeed, my bad i was mistaken :no_mouth:

**Comment by gittup** [comment]
No worries! Glad it's been working well so far :)

**Comment by Wetmelon** [comment]
Any chance of `import` coming to the Lua parser?  I'm running into an issue where my compiler looks for an environment variable to pick up the path to the license server, and the compiler can't escape the `tup` environment to do that :(

**Comment by gittup** [comment]
> Any chance of `import` coming to the Lua parser? I'm running into an issue where my compiler looks for an environment variable to pick up the path to the license server, and the compiler can't escape the `tup` environment to do that :(

Import should already work in the Lua parser, but if I'm understanding your use-case, you probably want export. Import is used to get the value of the environment variable into the Tupfile/Tupfile.lua so you can make decisions based on its value while parsing.
```
tup.import('SOMEENV')
if SOMEENV == 'debug' then
        tup.rule('echo build debug')
else
        tup.rule('echo build release')
end
```

If you change the value of SOMEENV, the Tupfile gets reparsed and potentially changes which rule gets created.

For your case, it sounds like you want the compiler to be able to access an environment variable, but tup has cleared that out before running it. To pass along extra environment variables, you can do:
```
tup.export('SOMEENV')
tup.rule( 'echo Env is: $SOMEENV')
```

Here, changing the value of SOMEENV won't trigger re-parsing the Tupfile, but it will trigger re-running the rule. Note that the export applies to all following rules in the Tupfile.

So I think you'll probably want tup.export('YOUR_LICENSE_ENV_HERE') somewhere before your compiler rules. You would only need import if there's some other logic you want to do in the parsing stage.
