### ISSUE TITLE
Feature Suggestion: Tupfile.base

### ISSUE THREAD

**Issue by ppannuto** [gittup/tup#132]
I've found it a minor weakness / annoyance of tup that the first time I check out a copy of a repo, I have to remember to run `tup init` before I can `tup upd`. There's a few challenges with running init automatically, the most obvious of which is knowing where the root of the project directory is (assuming it's the current directory feels risky).

My proposal is the addition of a new file: `Tupfile.base` (name flexible, maybe `Tupefile.root`, `Tupfile.ini`?)

This file would be placed in the root directory of the project to identify it. In addition to identifying the root, I would propose a simple syntax (currently thinking .ini-style syntax) for expressing things such as default variants for the project.

In my current mental model, this file is parsed if and only if tup cannot find a .tup directory. More specifically, as `tup upd` begins enumerating directories searching for the .tup directory, it also searches for Tupfile.base (after looking for .tup). If a Tupfile.base is found, the requisite commands are run to initialize things and then tup continues on with `upd`.

I'm willing to tackle implementing this feature, but I'd like some input on the design first. Is this a good / desirable idea? Do people have comments / suggestions for improving it?

**Comment by gittup** [comment]
I think we can close this, given the #133 has been merged.

**Comment by Qix-** [comment]
Why did we need an `.ini` file for this? I was always confused; whats wrong with just traversing upwards until we find a Tupfile, and if there isn't a `.tup/` in the same directory `tup init` gets called? This seems like the correct behavior. Git does this, and nobody has ever had a problem with it.

**Comment by gittup** [comment]
That's a good idea, though you may not have a Tupfile at the root of your project if you don't build anything there.

**Comment by ppannuto** [comment]
@Qix, Tupfile.ini was always part of a greater vision. Currently there is nowhere to store project-specific configuration for tup. Tupfile.ini was intended to be the home for that. See #144 for an old implementation of this as well as the beginning of this thread for some of the motivation.

As for recursing for Tupfiles, that wouldn't work in all scenarios. Easy example, we have some projects that use git submodules where recursing all the way to the "most root" Tupfile would not work correctly. At the same time, something like a `tup_root` directive in a Tupfile could solve this.

**Comment by Qix-** [comment]
@ppannuto recurse until a `.tup/` or a `Tupfile` or a `Tupfile.ini` is found. Pretty easy solution there. Doing _nothing_ is annoying.

Specifically saying where a parent Tupfile lives breaks the parent-child relationship, and makes no sense. Submodules that build with tup shouldn't have to know _anything_ about their parent.

As well, never said `Tupfile.ini` didn't serve a purpose, but having to make another file just so Tup can discover the original file is a little silly when you don't need `.ini` directives.

**Comment by ppannuto** [comment]
I think we have a miscommunication somewhere. Tup _does_ recurse right now, until it finds a Tupfile.ini indicating the root of the project it should build. The point is that you cannot correctly stop at the first Tupfile (plenty of Tupfiles in subdirectories of projects) or the "last" Tupfile (submodule example) you find.

W.r.t. parent-child, I think we agree. The current .ini system stops a tup call from a child submodule from recursing into the parent.

As for Tupfile.ini being another file, think of it more as a partially implemented feature perhaps? There was an intention to use the .ini directives.

The explicit goal was to eliminate the need to ever run `tup init`. There's a simple tradeoff in cognitive load there. In one case, a project maintainer creates a Tupfile.ini once, in the other case everyone who gets a copy of the project must remember to run `tup init` before doing anything. Sure, there's some precedent for a "init" command of some form (./configure; cmake -> make), but I'm not convinced that makes them good ideas / the right design choice (I would certainly prefer to just type cmake every time and have it call make. Right now you have the weird situation where every time _after_ the first time, make will pick up changes and re-run cmake for you, but the first time you have to remember to run cmake first. That feels broken IMHO. There's nothing fundamentally special about the first run.).

**Comment by Qix-** [comment]
First thing, pointing out that cmake doesn't just compile to make ;) Just being fair here. There's a reason why CMake exists aside from Make.

In cases that don't need a Tupfile.ini, though, why should I still have to type `tup init` when the Tupfile is literally _right there_?

**Comment by bradjc** [comment]
If you have this file structure:

```
/project
    Tupfile
    /library
        Tupfile
```

Tup allows you to run `tup` in the `/project/library` folder and it will build the whole project. If you didn't have a `Tupfile.ini`, and you ran `tup` on a new checkout in `/project/library`, it would put `.tup` in the wrong spot.

Now, someone could realize this was an issue and fix it if tup prints what it's doing and the person catches the mistake. However, if one wants to ensure one's tool doesn't get adoption and use by the community one makes it hard to use from the first command. If one wants people to actually give it a chance, one makes it as foolproof as possible. I think the current solution is the best approach for making tup easy to use.

**Comment by Qix-** [comment]
Eh? Running `tup` in `/project/library` would just traverse upwards and see the only viable configuration file is in `/project` and init there. What's the problem with that?

**Comment by ppannuto** [comment]
What is "the only viable configuration file" if not Tupfile.ini?

**Comment by ppannuto** [comment]
Recall, this is dealing with the case where the .tup directory does not yet
exist, so you cannot rely on that.

**Comment by Qix-** [comment]
@ppannuto A `Tupfile`?

**Comment by ppannuto** [comment]
Expanding on @bradjc's case:

```
/project
    Tupfile
    Tupfile.ini
    /submodule
        Tupfile
        Tupfile.ini
        /subfolder
             Tupfile
```

You type `tup` in the `subfolder` directory, what is the expected behavior? How does `tup` figure this out correctly without Tupfile.ini?

**Comment by Qix-** [comment]
Find the root-most `Tupfile.ini`.

**Comment by erikbrinkman** [comment]
Tup currently / soon will support a significant number of automatically generated files, e.g. Tup*{,.lua,.py}. Why not just treat any valid tup-specific file as a root marker, and define a precedence order?

On somewhat of a side note, but still relevant to what's decided. If Tupfile.ini is also intended as a root marker, shouldn't `tup init` create an empty one if it doesn't exist?

**Comment by Qix-** [comment]
@erikbrinkman No, because that introduces more fluff into the repository. Again, having two build files (`Tupfile` and `Tupfile.ini`) with one being completely meaningless if not used (`Tupfile.ini`) when they're both at the project root in smaller projects creates extra baggage in a repository.

I'd go so far as to vote to be able to have `Tupfile.ini` go away altogether and put those directives in the `Tupfile` or `Tupfile.lua` (`Tupfile.py`, whatever) files themselves.

**Comment by erikbrinkman** [comment]
@Qix- I assume you're responding to having `tup init` create a blank `Tupfile.ini`. I agree that if tup by default searches for the root most tup-specific file, then that's a bad thing. I'm specifically referring to the current behavior. Since currently tup searches for a `Tupfile.ini` if no `.tup` directory can be found, then it seems like `tup init` should also create one.

The reason why I included the suggestion to create a `Tupfile.ini` is because the optimal way to resolve all of these files hasn't been agreed upon in this thread, and the idea of creating a blank root market seems genuinely useful given the current behavior.

As for for removing `Tupfile.ini` all together, it seems good to separate tup options that aren't critical to the result of a tup build from the rules that specifically define the results of the build. I think Pat's original idea was that if you're defining options that are useful for a build, you might want to check them in, and it could also serve as an indicator of the tup root directory. There may be better places to put the configuration options than in Tupfile.ini, and I would probably prefer having a blank root `Tupfile` to a blank root `Tupfile.ini`, but I definitely don't think configuration options should go within a `Tupfile` given that by definition they do not affect the result of the build.

I can only assume that you agree with generally searching for any related tup-specific file instead of just `Tupfile`.
