### ISSUE TITLE
Generate and Variants?

### ISSUE THREAD

**Issue by ppannuto** [gittup/tup#249]
Unless I did something wrong, it looks like the generate command ignores variants?

I'm interested in generate for continuous integration testing, so I don't need to build all of the variants in one tree at the same time, but I do need to be able to pick up and set the different config variables.

What are your thoughts for something like

`tup generate --config configs/variant1 build.sh`
`tup generate --variant configs/variant1 build.sh`

to tell generate to use those config variables?

One generate script that can build multiple variants would be cool too, but I'm imagining a lot harder and not necessary :)

**Comment by gittup** [comment]
On Wed, Nov 18, 2015 at 6:52 PM, Pat Pannuto <notifications@github.com>
wrote:

> Unless I did something wrong, it looks like the generate command ignores
> variants?
>
> I'm interested in generate for continuous integration testing, so I don't
> need to build all of the variants in one tree at the same time, but I do
> need to be able to pick up and set the different config variables.
>
> What are your thoughts for something like
>
> tup generate --config configs/variant1 build.sh
> tup generate --variant configs/variant1 build.sh
>
> to tell generate to use those config variables?
>

Yeah, the generate command ignores variants, though it does read from the
top-level tup.config and uses that as the build configuration. Are you able
to copy configs/variant1 to tup.config before using generate? If that seems
problemsome, I think your suggestion is a good idea.


> One generate script that can build multiple variants would be cool too,
> but I'm imagining a lot harder and not necessary :)
>
For cases where generate is useful, it is probably beneficial to distribute
each variant to a different machine anyway. Though if we end up merging the
explicit-variants branch, this will become a lot easier to implement
(currently it is impossible since it relies on the dependency checker to
overlay the filesystem, which the generated shell script doesn't use).

-Mike

**Comment by gittup** [comment]
On Fri, Nov 20, 2015 at 2:42 PM, Mike Shal <marfey@gmail.com> wrote:

> On Wed, Nov 18, 2015 at 6:52 PM, Pat Pannuto <notifications@github.com>
> wrote:
>
>> Unless I did something wrong, it looks like the generate command ignores
>> variants?
>>
>> I'm interested in generate for continuous integration testing, so I don't
>> need to build all of the variants in one tree at the same time, but I do
>> need to be able to pick up and set the different config variables.
>>
>> What are your thoughts for something like
>>
>> tup generate --config configs/variant1 build.sh
>> tup generate --variant configs/variant1 build.sh
>>
>> to tell generate to use those config variables?
>>
>
> Yeah, the generate command ignores variants, though it does read from the
> top-level tup.config and uses that as the build configuration. Are you able
> to copy configs/variant1 to tup.config before using generate? If that seems
> problemsome, I think your suggestion is a good idea.
>
>
Actually, this was pretty straightforward to implement, so you should be
able to use the --config flag now (t2190). Give it a whirl and let me know
what problems you have with it.

Since you're using variants, can you try to use the explicit-variant branch
when you have a chance? I'd like to know if it's worth merging, or if it's
still too difficult to use.

Thanks!

**Comment by ppannuto** [comment]
This almost works, but it looks like generate isn't expanding groups. When
I tried it with this project
https://github.com/lab11/M-ulator/tree/master/simulator, the final build
step in the generated script was:

    cc %<objs> -pthread `python2-config --ldflags` -lrt -lm -o simulator

Hopefully an easy fix?

I'll give the explicit-variants branch a go right now
