### ISSUE TITLE
Out of date instructions for compiling with CONFIG_TUP_SUDO_SUID

### ISSUE THREAD

**Issue by chenglou** [gittup/tup#278]
When `updater.full_deps` is activated we get a warning that Tup should be recompiled with `CONFIG_TUP_SUDO_SUID=y`. The actual name, if I'm not mistaken, should be `TUP_SUDO_SUID`.

**Comment by gittup** [comment]
I believe this is correct, since the string to type into tup.config is "CONFIG_TUP_SUDO_SUID=y". The "CONFIG_" prefix is used for compatibility with the Linux kernel .config files. This variable can be referenced as either $(CONFIG_TUP_SUDO_SUID) or @(TUP_SUDO_SUID) in the Tupfile. See also the description of @-variables in the man page.

**Comment by chenglou** [comment]
Cool. Thanks!
