### ISSUE TITLE
tup internal error: Final pel missing for path: ''

### ISSUE THREAD

**Issue by siriobalmelli** [gittup/tup#301]
Hi, seem to be getting this error message on later versions of Tup (>0.7.5).

I've made a full dummy build tree that replicates the issue [here](https://github.com/siriobalmelli/tup_build_C).

Specific details on that error message are [here](https://github.com/siriobalmelli/tup_build_C/blob/master/TUP_BUGS.md).

I looked at the Tup sources very briefly and it wasn't immediately obvious to me what a `pel` is, so without direction it will likely take me a while to flounder around the source and figure out.

Any ideas?

Thank you very much.

**Comment by gittup** [comment]
It seems that tup was only looking for spaces, rather than any whitespace (like tabs) when splitting up the string. I should have a fix out shortly. In the meantime, you can change this line:

: foreach       $(EXE_LOCAL) |> !cc |> {exes}

to use a space instead of a tab:

: foreach $(EXE_LOCAL) ...

**Comment by gittup** [comment]
This should be fixed now - can you give it a try with the latest? Thanks for reporting the issue!

**Comment by siriobalmelli** [comment]
Thank you so much.
Confirmed working and updated [repo](https://github.com/siriobalmelli/tup_build_C) to reflect that :)
