### ISSUE TITLE
tup warning: unshare(CLONE_NEWUSER) failed error

### ISSUE THREAD

**Issue by kozross** [gittup/tup#310]
I just started trying to use tup, and on my first ``tup upd``, I got this error:

```
tup warning: unshare(CLONE_NEWUSER) failed, and tup is not privileged. Subprocesses will have '.tup/mnt' paths for the current working directory and some dependencies may be missed.
```

Should I be concerned? Is there a way to turn this off?

**Comment by gittup** [comment]
What type of system are you running it on (distribution, kernel version, etc)? The main issue would be if you use any build tools that care about CWD, for example using gcc with the -g flag embeds the path to the source file in the object file. Without namespacing, the path will look something like: /home/marf/test-dbug/.tup/mnt/@tupjob-12/home/marf/test-dbug rather than just /home/marf/test-dbug

You can run tup as 'TUP_NO_NAMESPACING=1 tup ...' to skip the code that generates the warning, but you still will potentially have the path issue.

Another option is to chown/chmod tup so that it is suid root, which should allow this to work. Eg:

sudo chown root:root tup
sudo chmod u+s tup

I think that should fix the pathing issue and also fix the warnings, but if not let me know.

**Comment by kozross** [comment]
@gittup I'm on Arch Linux. Kernel version, according to ``uname -r`` is ``4.10.13-1-ARCH``. I've never run into any CWD-related issues (I use clang as my compiler, so I'm not sure if -g will have the same issues there), but I'll give your fixes a try and see what happens.

**Comment by kozross** [comment]
@gittup I tried your solution (chown/chmod), and then tried to do a ``tup upd``. This is the output I got:

```
[koz@Sebastian evolog]$ tup upd
[ tup ] [0.000s] Scanning filesystem...
[ tup ] [0.161s] Reading in new environment variables...
[ tup ] [0.162s] No Tupfiles to parse.
[ tup ] [0.162s] No files to delete.
[ tup ] [0.162s] Executing Commands...
fusermount: option allow_other only allowed if 'user_allow_other' is set in /etc/fuse.conf
tup error: Timed out waiting for the FUSE file-system to be ready.
tup error: Unable to mount FUSE on .tup/mnt
```

**Comment by kozross** [comment]
Seemingly there's no issue with that. Thanks for your help!
