### ISSUE TITLE
Variants on windows

### ISSUE THREAD

**Issue by ruku320** [gittup/tup#334]
Variants don't work on the latest release for windows (tup-v0.7.5-58-ga9befa9).  It creates folders but doesn't execute any commands to build objects. There's a release from the explicit-variant branch (tup-explicit-variant-v0.7.3-45-gcf6a829) that works but it seems like it was created awhile ago (2015).  Are there any plans to get this functioning in the latest releases?

**Comment by datgame** [comment]
For Windows, I'm also still stuck on http://gittup.org/tup/win32/tup-explicit-variant-v0.7.3-45-gcf6a829.zip
Using a later version puts object files all over the source tree.
I think this bug is worth bumping, and wonder if there are any active developers on this project.
Also wondering if there are alternatives to tup; working in the same way, same philosophy and approach.
Happy to hear any suggestions. Currently I'm generating the Tupfiles from C++, so nothing is hand-written anyway.

**Comment by mitsukuri** [comment]
Can't help but bump.

**Comment by datgame** [comment]
I've moved on to CMake. It's terrible, but works most of the time.
Sad to see Tup dead and no working alternatives of the same kind.

**Comment by gittup** [comment]
Oof, it's hard to believe explicit-variant is that old. I'll try to update it and finally get it merged. My main sticking point has been backward compatibility -- I always feel terrible making others have to change their Tupfiles to fix my bad decisions. With explicit-variant, there are likely some changes that users will need to make to support them. But, I believe that's the best path forward for cross-platform support and for better tooling support (eg: issue #229). I'll try to update the branch and announce when it will be merged on the mailing list.

> I've moved on to CMake. It's terrible, but works most of the time.
> Sad to see Tup dead and no working alternatives of the same kind.

"dead" seems a bit much, given that there have been 2 releases and over a hundred commits in the last year. That doesn't mean there won't be long-standing issues that should've been fixed earlier, or that every pull request will be merged.

But since you are using CMake, a great way to help keep tup going would be for you to implement Tupfile generation in CMake. That would let people try out tup in existing CMake-based projects, and open it up to a wider audience.

**Comment by datgame** [comment]
Just dead from my point of view then :-) 
Things I wanted to rely on don't work, like this issue, and I think using it on encfs on Linux. I.e. Fuse I guess in general maybe. And the mixup of absolute and relative paths on Linux, which cause "#pragma once" to fail.
So i've been stuck with the old release to at least get some parts working on windows.
A CMake generator would indeed be interesting. Though I don't see myself doing that any year soon :-)

**Comment by LostTime76** [comment]
Just discovered tup recently. This tool seems to be a good step up for my use case of embedded C projects. From what I am reading, the one major feature I need is of course broken? I work on windows, and this is a show stopper. I need to be able to produce many build configurations (variants) based on different flags passed to the compiler and tools. Maybe I am doing something wrong as I am a n00b still, but when building for a variant, I shouldn't have to change the paths to my .o files in the tupfiles, right? For example running tup config1 should just put all of the .o files into a mirrored source tree of the config1 directory. Before you ask, yes, it appears I have the directory set up correctly with the tup.config file. tup config1 seems to be mirroring certain tree directories into the config1 directory but not actually building anything.

I really would like to introduce this tool to my team and company for embedded builds. I have a project that is starting basically now and I really really really really don't want to have to use cmake or meson garbage.

I have not done extensive research on output formatting, but one this is fixed, we can start to talk about formatting all of that output into something fully configurable. Alas, that is a conversation to be had later.

**Comment by gittup** [comment]
@LostTime76 I've actually just posted an update of the explicit-variant branch with some details on the mailing list: https://groups.google.com/g/tup-users/c/Fw5L-ii1VnI

In short, I'm planning to merge a branch that will enable variants on Windows in 2 weeks time. It is a backwards-incompatible change, hence the caution. However if you're creating a new project, you could try the test win32 build available here: http://gittup.org/tup/win32/tup-explicit-variant-v0.7.10-52-g6b2c469e.zip

I'm not sure what you're saying wrt output formatting - can you elaborate?

**Comment by LostTime76** [comment]
I went to the releases page and tried out everything with a release date of 5/1 already. Just to be sure, I redid the project with your zip posted in the comment just now and same issue. Here is a screenshot showing the most basic of use cases (I think). main.c in the project root with a debug (variant). I run tup debug on this directory and this is the output from fresh. I have tried multiple incantations of clang (not a clang expert, just using it to test), but it appears to be compiling the file fine just with the basic options. Additionally, I tried an 'in - source' build and it seemed to work fine. Variants are a requirement for our scenario.

With respect to output formatting. I don't know if its configurable and what tup currently spits out for 'status' info to the standard output is sufficient. However, we would like to heavily modify the output formatting.. or make it 100% configurable. For example, instead of using this built in formatting, instead have tup spit out formatting in raw csv format to be consumed by a script that executes the tup command and then regurgitates that back to the console as our desired output. We can have a conversation about what we are looking for if you are willing to provide such a feature set for tup. If not, we will find another way. The discussion is too big and off topic for this thread.
![Capture](https://user-images.githubusercontent.com/62843610/116826451-055c1e80-ab62-11eb-9759-cb1b41480214.JPG)

**Comment by gittup** [comment]
> I went to the releases page and tried out everything with a release date of 5/1 already. Just to be sure, I redid the project with your zip posted in the comment just now and same issue. Here is a screenshot showing the most basic of use cases (I think). main.c in the project root with a debug (variant). I run tup debug on this directory and this is the output from fresh. I have tried multiple incantations of clang (not a clang expert, just using it to test), but it appears to be compiling the file fine just with the basic options. Additionally, I tried an 'in - source' build and it seemed to work fine. Variants are a requirement for our scenario. Also keep in mind, I could be doing something very dumb, so just correct me. I only found tup yesterday...

With the explicit variants branch, you'll want to make use of the %-flags in the command strings in order for tup to substitute in the paths to the build directories. Tup is complaining here because the '-o main.o' causes clang to write main.o in the top-level directory, but tup is expecting the file to be created in the variant debug directory. Try this instead:

: main.c |> clang -c main.c -o %o |> main.o

Tup will substitute the path to the output in the variant directory for '%o'. Similarly, when you go to link your objects, instead of this:

: main.o |> clang main.o -o %o |> prog.exe

Use %f to specify the inputs:

: main.o |> clang %f -o %o |> prog.exe

**Comment by gittup** [comment]
> With respect to output formatting. I don't know if its configurable and what tup currently spits out for 'status' info to the standard output is sufficient. However, we would like to heavily modify the output formatting.. or make it 100% configurable. For example, instead of using this built in formatting, instead have tup spit out formatting in raw csv format to be consumed by a script that executes the tup command and then regurgitates that back to the console as our desired output. We can have a conversation about what we are looking for if you are willing to provide such a feature set for tup. If not, we will find another way. The discussion is too big and off topic for this thread.

Feel free to start another issue for this. The output is not currently configurable via the end-user (eg: in Tupfiles), though there are a few options that can be set to modify it (look up things like 'display.progress' and 'display.job_numbers', etc in the man page). Otherwise, you can always poke around in tup/src/tup/progress.c and try modifying things there.

As for having something else that executes the sub-process instead of tup, I think you'll have a bad time developing with this. There are certainly ways to get tup to list out the commands that need to run, but if you are running them outside of tup without its instrumentation in place, you won't get the automatic dependency detection and error checking that make tup so useful.

**Comment by LostTime76** [comment]
> 
> As for having something else that executes the sub-process instead of tup, I think you'll have a bad time developing with this. There are certainly ways to get tup to list out the commands that need to run, but if you are running them outside of tup without its instrumentation in place, you won't get the automatic dependency detection and error checking that make tup so useful.

You mis understand. Let's say I have a top level shell build script. The script is the one that executes tup [variant]. Tup then runs to completion spitting out all its output in csv format. The script reads the output stream line by line, splits it, and formats it.

**Comment by LostTime76** [comment]
Switching to using the %o in the tupfile worked for this use case by the way. Thanks

**Comment by gittup** [comment]
> You mis understand. Let's say I have a top level shell build script. The script is the one that executes tup [variant]. Tup then runs to completion spitting out all its output in csv format. The script reads the output stream line by line, splits it, and formats it.

Ahh yes I read that wrong. I thought you wanted tup to print out what commands it would execute and then have something else actually run them.

I don't see an issue including a csv-style output, especially if it's something that other tools already use and understand. You could add an option like "display.csv" to src/tup/option.c, and then check for it in src/tup/progress.c:show_result() and/or src/tup/updater:process_output(). I think that will get you most of the way there.

**Comment by gittup** [comment]
Explicit variants have been merged to the master branch, which now work on Windows.
