### ISSUE TITLE
"create_ignored_file() didn't get a final pel pointer" when using ignore pattern

### ISSUE THREAD

**Issue by haldean** [gittup/tup#375]
I'm trying to use the new wildcard-ignore feature to deal with a temporary file that Visual Studio's `link.exe` is creating. The file it creates is:

    C:/Users/willh/AppData/Local/Temp/lnk{DE4C5A64-96E7-44BC-BF56-1912B2574979}.tmp

where the UUID thing changes every time. I've been trying to ignore this file by using the pattern `^/AppData/`, which gives me the following error:

    tup internal error: create_ignored_file() didn't get a final pel pointer for file: C:/Users/willh/AppData/Local/Temp/lnk{9A59D35B-263F-4964-9947-7A295A4B2632}.tmp

My tup version v0.7.8-20-g1d2fd514, and I'm using the "x64 Native Tools" console in both VS2015 and VS2017.

Repro:

Tupfile:
```
: xd.c |> cl %f /c /Z7 /MD /Fo%o |> %B.o
: xd.o |> link %f /OUT:%o |> xd ^/AppData/
```

xd.c:
```
#include <stdio.h>

int main() {
  printf("hello world\n");
  return 0;
}
```

Gives me:

```
C:\Users\willh\code\tup-test>tup init
.tup repository initialized.

C:\Users\willh\code\tup-test>tup
[ tup ] [0.024s] Scanning filesystem...
[ tup ] [0.063s] Reading in new environment variables...
[ tup ] [0.092s] Parsing Tupfiles...
 0) [0.003s] .
 [ ] 100%
[ tup ] [0.129s] No files to delete.
[ tup ] [0.160s] Generating .gitignore files...
[ tup ] [0.207s] Executing Commands...
 1) [0.136s] cl xd.c /c /Z7 /MD /Foxd.o
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23918 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

xd.c
* 0) link xd.o /OUT:xd
Microsoft (R) Incremental Linker Version 14.00.23918.0
Copyright (C) Microsoft Corporation.  All rights reserved.

 *** tup messages ***
tup internal error: create_ignored_file() didn't get a final pel pointer for file: C:/Users/willh/AppData/Local/Temp/lnk{783FC4DA-EFAC-4B09-B286-E25C5562114E}.tmp
 *** Command failed due to errors processing the output dependencies.
 [  ] 100%
 *** tup: 1 job failed.
```

(Alternatively, if anyone knows how to get VS2015 or VS2017 to stop writing these temp files I'd love to know!)

**Comment by haldean** [comment]
Actually, here's a much simpler repro:

Tupfile:
```
: xd.c |> cl %f /c /Z7 /MD /Fo%o |> %B.o
: xd.o |> link %f /OUT:%o |> xd ^/AppData/
```

xd.c:
```
#include <stdio.h>

int main() {
  printf("hello world\n");
  return 0;
}
```

Gives me:

```
C:\Users\willh\code\tup-test>tup init
.tup repository initialized.

C:\Users\willh\code\tup-test>tup
[ tup ] [0.024s] Scanning filesystem...
[ tup ] [0.063s] Reading in new environment variables...
[ tup ] [0.092s] Parsing Tupfiles...
 0) [0.003s] .
 [ ] 100%
[ tup ] [0.129s] No files to delete.
[ tup ] [0.160s] Generating .gitignore files...
[ tup ] [0.207s] Executing Commands...
 1) [0.136s] cl xd.c /c /Z7 /MD /Foxd.o
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23918 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

xd.c
* 0) link xd.o /OUT:xd
Microsoft (R) Incremental Linker Version 14.00.23918.0
Copyright (C) Microsoft Corporation.  All rights reserved.

 *** tup messages ***
tup internal error: create_ignored_file() didn't get a final pel pointer for file: C:/Users/willh/AppData/Local/Temp/lnk{783FC4DA-EFAC-4B09-B286-E25C5562114E}.tmp
 *** Command failed due to errors processing the output dependencies.
 [  ] 100%
 *** tup: 1 job failed.
```

**Comment by miguelcartaxoZPX** [comment]
Having the same issue, any luck?

**Comment by haldean** [comment]
Nope, spent a little bit of time trying to understand the code before I gave up and switched to makefiles instead :(

**Comment by miguelcartaxoZPX** [comment]
I have a makefile for my project on windows but it uses GCC and its kind of slow. Everytime I go back to it to add something I always forget exactly what does what and how. The syntax is so obtuse. I've tried Tup before for a simple project and it worked great on linux with GCC, now I wanted to use CL and LINK on windows but it seems it does not work all that well with Tup (at least the cl/link 2017 version). 

Also tried NMAKE, it was fast but could not figure out how to make it compile if I change a header file. Tup detects this by default and with Make I can add the .d files logic to it for file dependency (its annoying but it works). NMake has a cool thing called batch-mode rules, which allow CL to be called only once and compiles several cpp files which complements well with the /MP flag for multithreading (which makes no difference in Tup, I think because the "foreach" in the rule calls CL separately, not sure). 

Anyway, sorry for going a bit off-topic. I would still be interested in a solution for this issue.

**Comment by thekitchensink** [comment]
The PR above fixes this issue, if you need binary files for the build I can post them.
