### ISSUE TITLE
Circular dependency using !tup_preserve

### ISSUE THREAD

**Issue by ffreling** [gittup/tup#388]
I have an issue with `!tup_preserve` that is similar to #302 (since the previous issue is closed, I open a new one).

I use tup for generating a static website and for each image I want to copy the original image to the variant directory and also generate a thumbnail for it.

Here is a snippet of my (simplified) `Tupfile`:
```
: asset.raw |> !tup_preserve |>
: asset.raw |> cp %f %o |> %B.thumbnail
```

This works as expected. However, as soon as I modify the `Tupfile`, rebuilding fails with the following message: ` tup error: Command ID 15 lists this file as both an input and an output: build-default/asset.raw`.

It only works on fresh build, not on incremental ones.

I also tried to use `foreach` rules to apply it to all my images:
```
: foreach *.raw |> !tup_preserve |>
: foreach *.raw |> cp %f %o |> %B.thumbnail
```
but it fails with another message: `tup error: Unable to create output file 'asset.thumbnail' because it is already owned by command 18.`

I was able to rewrite it using a simple script that generate rules for each asset. However if it is possible to use `foreach` in my use case I would like to know. I think the syntax much nicer.

Environment
----------------
- tup 0.7.8
- Arch Linux / macOS Mojave

How to reproduce
----------------------
I made a small repository to exhibit the issue:
1. `git clone https://git.sr.ht/~ffreling/tup-recipes`
2. `cd thumbnails`
3. `./preserve_bug.sh`

**Comment by ffreling** [comment]
Actually, the bug occurs with only the first line in `Tupfile`:
```
: asset.raw |> !tup_preserve |>
```

This can be reproduce with simpler steps:
```sh
$ tup init
$ touch foo.txt
$ mkdir build
$ touch build/tup.config
$ echo ": foo.txt |> !tup_preserve |>" > Tupfile
$ tup
$ touch Tupfile
$ tup
```

This fails with the following output (via `tup -d`):
```
 tup -d
[ tup ] [0.000s] Scanning filesystem...
[ tup ] [0.001s] Reading in new environment variables...
[tup.updater:7009 graph.c:359] find deps for node: 6
[tup.updater:7009 graph.c:374] remove node from stack: 6
[ tup ] [0.002s] Parsing Tupfiles...
[tup.updater:7009 updater.c:1695] root node: 0
[tup.updater:7009 updater.c:1709] cur node: 6
[tup.updater:7009 file.c:131] received file 'Tupfile' in mode 0
* 0) [0.005s] build
tup error: Command ID 13 lists this file as both an input and an output: build/foo.txt
tup error: Error parsing Tupfile line 1
  Line was: ': foo.txt |> !tup_preserve |>'
 [ ] 100%
 *** tup: 1 job failed.
```

**Comment by gittup** [comment]
Thanks for reporting this! I think it should be fixed in the latest master. Let me know if you have further issues with !tup_preserve.

**Comment by ffreling** [comment]
Thanks for updating tup! I really like this project and I'm glad it's still kicking!

I tried the `44a4a4ce` revision but I hit another issue.

Here is my Tupfile:
```
: asset.raw |> !tup_preserve |>
: asset.raw |> cp %f %o |> %B.thumbnail
```

The first rule with `!tup_preserve` seems to work but since I am using variant in `build-default`, it actually creates a wrong symlink:

```
~/C/t/thumbnails (master|…) |> tree
.
├── asset.raw
├── build-default
│   ├── asset.raw -> .
│   └── tup.config
├── preserve_bug.sh
├── Tupfile
└── Tupfile.ini
```

I think the symlink in `build-default` should point to the `asset.raw` in the top directory.
Other targets depending on `asset.raw` fail afterwards, because in the variant `build-default`, `asset.raw` points to a directory.

Should I open another issue for this?

The sample code is available at: http://code.ffreling.com/fabs/tup-recipes

**Comment by gittup** [comment]
On Wed, May 27, 2020 at 9:19 AM Fabien Freling <notifications@github.com>
wrote:

> Thanks for updating tup! I really like this project and I'm glad it's
> still kicking!
>
Thanks for documenting issues!

> I tried the 44a4a4ce revision but I hit another issue.
>
> Should I open another issue for this?
>
It doesn't matter much to me, though if I don't see the email it's probably
unlikely I'll look at a closed issue again. So if you want to keep it all
in one place just make sure to re-open it.

> The sample code is available at: http://code.ffreling.com/fabs/tup-recipes
>
Thanks, that was helpful. This is a bit hard to reason about because
variants were designed as a kind of file-system overlay, so files in the
srcdir and build dir combine to make the full picture available to the
subprocess. As part of that, it is unexpected that the srcdir and build dir
would contain files with the same name. However, !tup_preserve breaks that
because it copies the srcdir file into the build dir, so tup has to think
about both "file" and "build/file" as separate entities in some contexts,
and treat them similarly in others (eg: when listed as an input). So, that
is why it is hard to get right, and I wouldn't be surprised if you hit
further issues.

I added a few more test cases that I could think of, and made sure at least
your sample code now works as far as I can tell. Please report back if you
find others.

Thanks,
-Mike

**Comment by ffreling** [comment]
I can confirm it now works at revision `c1d374e67a8803718d4a28045300cc85eff1336a`.
Thanks again for fixing it. :tada: 

I'm not sure I can reopen an issue if it's been closed by someone else, but I don't mind. I'll open another issue if I encounter a bug.
