### ISSUE TITLE
Is injection safe?

### ISSUE THREAD

**Issue by playgithub** [gittup/tup#389]
In the latest release for Windows, there are two files:
* `tup-dllinject.dll`
* `tup-dllinject32.dll`

I'm afraid of malware.
Are they safe? What do they do?

Thanks

**Comment by gittup** [comment]
Those dlls aren't malware - they're built as part of tup. You can see the source code here: https://github.com/gittup/tup/tree/master/src/dllinject

The dlls are only used for the Windows version, and enable tup to automatically determine dependencies of subprocesses invoked during your build. So when you write a rule in a Tupfile like so:

`: |> gcc -c foo.c -o %o |> foo.o`

tup will inject the dll into the gcc process in order to determine what files are read from & written to. On Linux and MacOS, a FUSE filesystem is used to determine dependencies. Linux also supports a shared library shim, which is similar to the DLL injection used in Windows.

Does that answer your question?

**Comment by playgithub** [comment]
Injecting into the compiler is extremely efficient. But how to know which files has been changed externally (e.g. editing) in this way?

**Comment by gittup** [comment]
The dependency detection only looks at files read/written to by the subprocesses invoked by tup, which is only used to add links to the DAG and verify that the build configuration is correct (so tup can produce an error message if one process writes to a file, and another process reads from the file but doesn't have that dependency specified in the Tupfile). Knowing which files are changed externally by the user is a separate problem and uses a different set of algorithms.

By default tup looks for which files have changed by scanning the filesystem. Since this is inefficient (an O(n) algorithm), tup also supports using a file monitor program to supply the list of files that have changed, but that currently only works on Linux (see the `tup monitor` command).

If you know you're only going to be changing files via an IDE, it may be possible to modify the IDE or write a plugin that could notify tup whenever a file is modified, which would allow you to skip the scan with the --no-scan argument. That would likely involve a bit of work and require you to be familiar with the IDE though.

**Comment by playgithub** [comment]
Got it. `tup monitor` is the thing I'm intrested in.
Thanks

**Comment by gittup** [comment]
If you're just interested in the file monitor, you might want to take a look at watchman: https://facebook.github.io/watchman/
