### ISSUE TITLE
Build fails on 32 bit systems

### ISSUE THREAD

**Issue by lgbaldoni** [gittup/tup#410]
```
  bootstrap CC -fomit-frame-pointer -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DTUP_SERVER="fuse3" -DHAVE_CONFIG_H ../src/tup/server/fuse_fs.c
In file included from /usr/include/fuse3/fuse.h:19,
                 from ../src/tup/server/tup_fuse_fs.h:32,
                 from ../src/tup/server/fuse_fs.c:29:
/usr/include/fuse3/fuse_common.h:853:1: error: static assertion failed: "fuse: off_t must be 64bit"
  853 | _Static_assert(sizeof(off_t) == 8, "fuse: off_t must be 64bit");
      | ^~~~~~~~~~~~~~
```

Should I just use fuse2 with it?

**Comment by gittup** [comment]
fuse2 would probably work, since pkg-config for fuse2 gives -D_FILE_OFFSET_BITS=64, while fuse3 no longer does apparently. Can you also try this patch? (Note: untested)

diff --git a/Tuprules.tup b/Tuprules.tup
index 153fac75..6a9e4253 100644
--- a/Tuprules.tup
+++ b/Tuprules.tup
@@ -95,6 +95,7 @@ ifeq ($(TUP_SERVER),fuse3)
 export PKG_CONFIG_PATH
 CFLAGS += `pkg-config fuse3 --cflags`
 CFLAGS += -DFUSE3
+CFLAGS += -D_FILE_OFFSET_BITS=64
 endif
 
 ifeq ($(TUP_SERVER),ldpreload)
diff --git a/build.sh b/build.sh
index e165f9da..32ce1daf 100755
--- a/build.sh
+++ b/build.sh
@@ -18,7 +18,7 @@ if [ "$server" = "fuse" ]; then
 	plat_ldflags="`pkg-config fuse --libs`"
 	plat_files="$plat_files ../src/tup/server/fuse*.c ../src/tup/server/master_fork.c"
 elif [ "$server" = "fuse3" ]; then
-	plat_cflags="`pkg-config fuse3 --cflags` -DFUSE3"
+	plat_cflags="`pkg-config fuse3 --cflags` -DFUSE3 -D_FILE_OFFSET_BITS=64"
 	plat_ldflags="`pkg-config fuse3 --libs`"
 	plat_files="$plat_files ../src/tup/server/fuse*.c ../src/tup/server/master_fork.c"
 elif [ "$server" = "ldpreload" ]; then

The first part is for tup building itself, and the second part is for building the bootstrapped version (which is where you're hitting the error).
