### ISSUE TITLE
Security warning in chrome

### ISSUE THREAD

**Issue by keithlayne** [gittup/tup#411]
I don't know a better way to communicate this to you, so here goes.

Visiting gittup.org/tup I get:

![image](https://user-images.githubusercontent.com/2667202/97827820-5f535880-1c93-11eb-940c-d332eb573a63.png)

I was just on the site the other day and didn't see this warning. Google apparently doesn't give specific details for why.

**Comment by keithlayne** [comment]
Update: today I tried again out of curiosity, and got this error:

## gittup.org is blocked

Requests to the server have been blocked by an extension.
Try disabling your extensions.
ERR_BLOCKED_BY_CLIENT

So...maybe the issue is on my end?  Although I'm pretty sure I got independent confirmation on the original error page.

**Comment by andremarcais** [comment]
I have the same issue (the original, not the thing with the extension).

**Comment by gittup** [comment]
This happened last time I pushed out changes too. Apparently something in the pre-built Windows binaries is triggering some malware detection software they have, though I can't find any details as to why. Last time I requested a review and it went back to normal after a few days, but this time the review failed. Unfortunately, it doesn't give any details about that either.

@wanderview, any idea who at Google works on this? I'd appreciate your advice, or if you can, point me in the right direction to get answers. The association of tup with malware is obviously harmful to me and to tup's users and potential users. How can I prevent my website being blocked every time I push new commits to tup?

**Comment by keithlayne** [comment]
Sorry you're having to deal with this, but sounds like you're on it. I'm not on windows either, so I guess it's a blanket thing.  I'll leave this open for now I guess.

**Comment by wanderview** [comment]
I filed an escalation issue internally.

**Comment by gittup** [comment]
Thank you!

**Comment by gittup** [comment]
I spent the last several days testing things out on virustotal. I was expecting there to be an issue with the DLL injection in the Windows binaries, but tup.exe and the .dll files all report no issues. The main culprit, as Gerhard clued me into on the mailing list, is tup32detect.exe. When this file is tested in virustotal, it reports some 20+ engines detecting it as malware. The source code for it is basically a hello-world:

```
#include <windows.h>
#include <stdio.h>

int main(void)
{
	int ll = (int) LoadLibraryA;
	int gpa = (int) GetProcAddress;
	printf("%x-%x\n", ll, gpa);
	ExitProcess(0);
}
```
It gets compiled by tup with:

```
i686-w64-mingw32-gcc -c tup32detect.c -o tup32detect.o32 -w
i686-w64-mingw32-gcc src/compat/win32/detect/tup32detect.o32 -o tup32detect.exe -static-libgcc
```

Where the MinGW compiler is version gcc version 9.3-win32 20200320. Apparently hello-world compiled with MinGW is a bit notorious for causing various AV software to get confused and mis-categorize it.

Playing around with various compiler flags, I was able to discover that rebuilding it with -D__USE_MINGW_ANSI_STDIO=1 lowers the false-positive rate in virustotal down to 3 engines, so I committed 86a8531c8 to see if that will help going forward. Unfortunately it doubles the size of tup32detect, but hopefully that does not have a significant impact.

I'm not sure how reliable virustotal is though, or how it relates to Google's own detection of what constitutes malware. For example, I told it to scan the URL http://gittup.org/tup/win32/tup-v0.7.10.zip, and it reports 3 engines detecting it as malware. But if I download that zip file to my local machine, and then upload it to scan, virustotal reports 41 engines detecting the file. Both reports show the same sha256 hash of f9b8afd3ad2fad873ce02d79a76d1c7cf86a74f5f783827e970fa082f2fbabf5. (NOTE: I have since replaced tup-v0.7.10.zip with a version that has a tup32detect.exe re-compiled with -D__USE_MINGW_ANSI_STDIO=1, so if you download the file, you will have a different version. If anyone wishes to reproduce this experiment, I can send you the original tarball).

I have also found that newer versions of MinGW (I tested 10.2.0) produce a hello-world.exe with fewer hits (3 engines, same as the older version with the magic define flag added). However, I imagine that can be a moving target if AV software catches up to the latest technology of hello-world malware.

I'm not sure if this change is enough to get the website unblocked, or if it will get blocked again the next time I push out code. I wanted to document what I found so far, since I don't have any other information to go on at this point.

**Comment by wanderview** [comment]
I think your change in the previous comment may have helped.  Also, the escalation has been fixed, so hopefully this won't happen again.  Let me know if it does.  Thanks.

**Comment by Wetmelon** [comment]
Huh.  Yeah, I had tup32detect.exe flag as a virus at work and IT wanted to re-image my computer lol.  And then it happened at home.  In both cases (Symantec Endpoint and Windows Defender, respectively), I was able to submit it for review and get it appealed with no issues.  It did cause issues for a bit there though.  Glad you looked into it!

We use tup for an open source project and some other people had issues:
https://discourse.odriverobotics.com/t/tup-warning-to-windows-users-and-firmware-upgrade/3874
https://discourse.odriverobotics.com/t/windows-10x64-firmware-make-error/2810/2
https://discourse.odriverobotics.com/t/problems-with-toolchain/1925

**Comment by gittup** [comment]
> I think your change in the previous comment may have helped. Also, the escalation has been fixed, so hopefully this won't happen again. Let me know if it does. Thanks.

Awesome, thanks! Looks like it is working again, and the search console reports no issues detected.

**Comment by gittup** [comment]
> We use tup for an open source project and some other people had issues:
> https://discourse.odriverobotics.com/t/tup-warning-to-windows-users-and-firmware-upgrade/3874
> https://discourse.odriverobotics.com/t/windows-10x64-firmware-make-error/2810/2
> https://discourse.odriverobotics.com/t/problems-with-toolchain/1925

Ahh, sorry to hear that. Can you confirm that this is working now with v0.7.10 or later?

> One option may be to use the TDM GCC https://jmeubank.github.io/tdm-gcc/ tools or even clang / llvm rather than using the MSYS2/MinGW stuff

That's definitely something to consider. Though as I noted in another comment, newer MinGW versions don't seem to have this problem. Hopefully this won't be an issue going forward!

**Comment by gittup** [comment]
I believe the compiler flag changes have resolved this. It hasn't been reported since that landed, so I'm closing the issue.
