### ISSUE TITLE
tup varsed not compatible with tup generate?

### ISSUE THREAD

**Issue by ryanford** [gittup/tup#418]
Running a script successfully generated by `tup generate` fails to run with error message `tup client error: Couldn't find path for 'tup_vardict'`

tup version: tup v0.7.10-7-gb38dbfc8
host os: lubuntu linux 20.04

**Comment by ryanford** [comment]
`tup` runs successfully, I only get error when running the generated build script

**Comment by gittup** [comment]
Thanks for the report! The fix was fortunately pretty straightforward -- 'tup generate' now also creates a 'tup-generate.vardict' file alongside the build script, and the build script adds the environment variable that 'tup varsed' is looking for.

I just added two quick tests for it -- report back if you come across other issues trying to use it.

**Comment by ryanford** [comment]
works great, thanks for the quick fix
