### ISSUE TITLE
gitignore is always being ignored by itself

### ISSUE THREAD

**Issue by EV3R4** [gittup/tup#421]
When tup creates a gitignore file, it is always ignoring itself.
This can be problematic when you need to exclude files generated by the program.

**Comment by EV3R4** [comment]
A possible solution for this would be to add an option (to/to not ignore itself) to `.gitignore`.

**Comment by gittup** [comment]
I made it so .gitignore is not ignored if there is any user-generated content, so you shouldn't need to do anything special going forward (though, you may need to touch the Tupfile so that it gets re-parsed, since I didn't bump the parser version). Let me know if there are cases where it's not working correctly.

**Comment by gittup** [comment]
Fixed by 627aa5659b2f.
