### ISSUE TITLE
Problem with ^t^

### ISSUE THREAD

**Issue by petemoore** [gittup/tup#428]
I think I've found an issue. To reproduce, create this script and run it:

```
#!/bin/bash
rm -rf tmp
mkdir tmp
cd tmp
tup init
echo ': |> ^t^ echo hello > %o |> msg.txt' > Tupfile
# tup
echo ': msg.txt |> cat %f > %o |> msg_copy.txt' >> Tupfile
tup
```

You should get the `msg_copy.txt` file created for you in the `tmp` directory.

Now uncomment the first `tup` command that is commented out above:

```
#!/bin/bash
rm -rf tmp
mkdir tmp
cd tmp
tup init
echo ': |> ^t^ echo hello > %o |> msg.txt' > Tupfile
tup
echo ': msg.txt |> cat %f > %o |> msg_copy.txt' >> Tupfile
tup
```

This time, you don't get the `msg_copy.txt` file, no matter how many times you run `tup` in the `tmp` subdirectory.

**Comment by gittup** [comment]
Thanks for the script to reproduce! There are two issues going on here.

First, tup only tracked files with 1-second resolution, so when scripting I would use 'tup touch [filename]' to tell tup that a file had changed when doing something like 'tup; change file; tup' in a test script. Otherwise after the first update, when you append to the Tupfile, tup sees that the Tupfile has the same mtime as what it last parsed and doesn't re-parse it. So the test script would need to be:

```
#!/bin/bash
rm -rf tmp
mkdir tmp
cd tmp
tup init
echo ': |> ^t^ echo hello > %o |> msg.txt' > Tupfile
tup
echo ': msg.txt |> cat %f > %o |> msg_copy.txt' >> Tupfile
tup touch Tupfile
tup
```

(Also I'd recommend looking at the scripts in tup/test/, and using one of those as a framework. Those take care of creating a tmp directory and cleaning it up on a successful test run.)

Updating to more accurate timestamps has long been on my radar, but I got so used to sprinkling 'tup touch's in the test scripts that I never got around to it. So I finally did that in commit b5e39d33097bda55c2e0731b9a1f8f5882ed4157 to add nanosecond resolution timestamps, and now you no longer need the 'tup touch'. (If you want to run your script on a version prior to that commit, you'll need 'tup touch' to accurately compare the behavior. When you do this you'll see that the Tupfile is re-parsed, but the second command fails because msg.txt doesn't exist).

The second issue is the issue with the ^t flag itself. Tup was only bringing in transient commands if the downstream command had actually read from the file on a prior invocation, rather than if a dependency was declared in the Tupfile (this is the 'normal' links vs. 'sticky' links in the tup code). Normal links are only added on an input file after the command runs the first time, so the transient command wasn't getting added to the DAG. The correct thing to do here is to add transient commands based on sticky links, which commit b5e39d33097bda55c2e0731b9a1f8f5882ed4157 should fix.
