### ISSUE TITLE
Cannot move files

### ISSUE THREAD

**Issue by BeastyBlacksmith** [gittup/tup#435]
I am testing this simple `Tupfile`
```
: |> touch a.in |> a.in
: a.in |> mv %f %o |> a.out
```
but I get the error
```
* 0) mv a.in a.out                                                                                                                                                                                  
mv: cannot move 'a.in' to 'a.out': No such file or directory
```
while it works perfectly fine if I do it on the command line.

Am I doing conceptionally wrong?

**Comment by gittup** [comment]
It doesn't really make sense to move files as a separate rule. Even if you could, tup would notice that the intermediate file (a.in in this case) is missing, and then try to re-create it.

I assume you have some use-case where the initial command can't create the desired output file in the first place? If so, you could wrap the invocation so that the mv is included in it (either with a separate shell script, or just in the rule itself). Eg:

`: |> touch a.in && mv a.in a.out |> a.out`

If it's some oddball tool that doesn't take an output flag and you need to use frequently, a wrapper script would be the way to go so you can force an output flag onto the tool. Something like:

```
$ cat mytouch.sh 
output="$1"
shift
# Note: Use the real command and pass in its args with "$@" or some such.
touch a.in
mv a.in $output
```

```
$ cat Tupfile 
: |> ./mytouch.sh %o |> a.out
```

**Comment by BeastyBlacksmith** [comment]
Yeah, my usecase is that I want to redirect only some of the output and not all, but putting it in one rule works out, thanks!
