### ISSUE TITLE
Build with variants broke for me after commit 89bcc36c96a0011d704641cdce79bfe900b12feb

### ISSUE THREAD

**Issue by skarupke** [gittup/tup#459]
Hi, a project of mine that is using variants broke when I updated to a new version of tup. I used git bisect to find that commit [89bcc36c96a0011d704641cdce79bfe900b12feb](https://github.com/gittup/tup/commit/89bcc36c96a0011d704641cdce79bfe900b12feb) is the one that caused the problem. Before the commit, the build worked. After the commit, it doesn't work. I attached a stripped down version of the build that just runs a single build step (it calls "echo" to write text to a file):

[tup_variant_reproduce.zip](https://github.com/gittup/tup/files/8550215/tup_variant_reproduce.zip)

The error message says both "you didn't write a file that you claimed you would write" and "you wrote a file that you didn't claim you would write" even though it's the same file. Here is an example output:

```
*  2) build-clang-debug: echo "Signature: 8a477f597d28d172789f06886806bc55" > libs/CACHEDIR.TAG                                                                         
 *** tup messages ***
tup error: Expected to write to file 'libs/CACHEDIR.TAG' from cmd 97 but didn't
tup error: Unspecified output files - A command is writing to files that you didn't specify in the Tupfile. You should add them so tup knows what to expect.
 -- Unspecified output: libs/CACHEDIR.TAG
 *** Command failed due to errors processing the output dependencies.
```

Let me know if I'm using variants incorrectly, but this used to work.

This is on Ubuntu 20.04, with tup compiled on commit 89bcc36c96a0011d704641cdce79bfe900b12feb. (it works on the commit before)

**Comment by uohmak4fvpqe** [comment]
There was a breaking update with variants at the date of that commit, maybe that helps:
[https://github.com/gittup/tup/issues/434#issuecomment-917600735](url)

**Comment by gittup** [comment]
Sorry for the delay. There is some more background info on this mailing list post: https://groups.google.com/g/tup-users/c/Fw5L-ii1VnI/m/iTvR7A9AAgAJ

In general, try to use %f, %o, and other %-flags to refer to files in the commandline. So instead of appending the 'output' variable, use %o like this:

`command = 'echo "Signature: 8a477f597d28d172789f06886806bc55" > %o',`

This lets tup replace the local path with the variant path.

In some cases, you may need to use $(TUP_VARIANTDIR) to refer to the variant directory. For example, to include generated headers you will need something like `-I$(TUP_VARIANTDIR)` as a compiler flag in order to find them.

This was an intentional breaking change in order to get variants working with Windows and debuggers like gdb. If you need to, stick with the v0.7.11 release, which was the last release with the older FUSE-overlay style variants. Let me know if you have other issues with the explicit variants!

**Comment by gittup** [comment]
> The one thing that could have been better is a clear place to communicate this breaking change on the homepage. I don't usually search through mailing lists when I encounter problems.

That's a good point. I made a note to add something to the webpage before doing the v0.8 release.

> Also you may want to update the lua examples page because my build script was exactly following those: https://gittup.org/tup/ex_lua_examples.html (e.g. search for "function compile" which would break with variants)

Thanks for catching that! I've updated the lua examples. I tested a few of them to make sure they work with variants, but I didn't run through all of them.
