### ISSUE TITLE
0.7.11 looks for generated intermediate file outside of variant folder instead of within it

### ISSUE THREAD

**Issue by suchipi** [gittup/tup#464]
I recently switched from `tup 0.7.8-3 [debian]` to `tup v0.7.11-84-gc8bca8d8`. It initially went fine, but my build stopped working after clearing out my tup db.

In my project, part of it is built like so:
- build a program that makes header files
- run the program
- consume the generated header files in another program

When I do that second step, running the program, I do it by running the generated binary, using eg `./gen-header`.

In 0.7.8, that `./gen-header` resolves to `<variant-dir>/src/path/to/gen-header`, but 0.7.11 tries to find it in `src/path/to/gen-header`. Expected behavior is that they would both look in the variant dir.

I've created a repro here with more information: https://github.com/suchipi/tup-464-repro

The actual project is more complicated, so the structure of the repro repo is contrived; it's just the minimum for reproducing the bug.

**Comment by gittup** [comment]
This is a result of the explicit-variant merge. Some details from the mailing list are here: https://groups.google.com/g/tup-users/c/Fw5L-ii1VnI/m/iTvR7A9AAgAJ

The TL/DR is in order to get variants working on Windows and with tools like gdb, your Tupfiles now need to be aware that variants exist. Previously it was done almost entirely transparently by using a FUSE filesystem overlay, which worked great until you tried to do things like run your program in a debugger.

For the first part of finding ./gen-header, I recommend using flags like %f, %o, etc as much as possible. This will let tup translate the path to the variant path when appropriate. For example:

`: gen-header |> ./%f >> %o |> generated-header.h`

For the second part of finding generated header files, you'll need to pass in a -I flag using $(TUP_VARIANTDIR). TUP_VARIANTDIR evaluates to the current directory (eg: where the Tupfile resides), but inside the variant. So the compilation rule can be:

`: myprog.c | generated-header.h |> gcc %f -o %o -I$(TUP_VARIANTDIR) |> myprog`

Those two steps (using %-flags where possible, and adding $(TUP_VARIANTDIR) where %-flags don't work) should get variants working again. Also note that if you aren't using variants, TUP_VARIANTDIR expands to '.', so with the above changes it should build both with and without variants enabled. Let me know if you are having further issues in your larger project with that fixed.

Note that this is obviously a breaking change, which is why the next release after v0.7.11 will be v0.8 (so if you need the old variant behavior for some reason, stick with the v0.7.11 release for now.

**Comment by suchipi** [comment]
Makes sense; thank you! Thanks for the detailed writeup and guide on how to convert Tupfiles :D
